name: dev_helper
description: Some helper functions such as logger.
version: 0.0.1
homepage: https://github.com/chenzhiguang/dev_helper

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
